export const theme = {
  light: {
    background: '#ffffff',
    foreground: '#000000',
    primary: '#3b82f6',
    'primary-foreground': '#ffffff',
    secondary: '#f3f4f6',
    'secondary-foreground': '#1f2937',
    muted: '#f3f4f6',
    'muted-foreground': '#6b7280',
    accent: '#f3f4f6',
    'accent-foreground': '#1f2937',
    destructive: '#ef4444',
    'destructive-foreground': '#ffffff',
    border: '#e5e7eb',
    input: '#e5e7eb',
    ring: '#3b82f6',
  },
  dark: {
    background: '#0f1117',
    foreground: '#ffffff',
    primary: '#3b82f6',
    'primary-foreground': '#ffffff',
    secondary: '#1a1d24',
    'secondary-foreground': '#ffffff',
    muted: '#1a1d24',
    'muted-foreground': '#9ca3af',
    accent: '#1a1d24',
    'accent-foreground': '#ffffff',
    destructive: '#ef4444',
    'destructive-foreground': '#ffffff',
    border: '#1f2937',
    input: '#1f2937',
    ring: '#3b82f6',
  },
};
